server:
  port: 8090

spring:
  application:
    name: chat-persistence-node
  profiles:
    active: local

  cassandra:
    schema-action: create-if-not-exists
    keyspace-name: chat_test_keyspace
    local-datacenter: datacenter1